site_name: Darkly - cuadernos de investigación
nav:
  - Home: index.md
  - Breaches:
    - SQL Injection - Users: breaches/sql_injection_users.md
    - SQL Injection - Images: breaches/sql_injection_images.md
    - Web Crawling: breaches/web_crawling.md
    - Local File Inclusion: breaches/local_file_incusion.md
    - Http Proxying: breaches/http_proxying.md
    - Insecure Authentication Method: breaches/insecure_authentication_method.md
    - Open Redirect Vulnerability: breaches/open_redirect.md
    - Cookie Tampering: breaches/cookie_tampering.md
    - XSS Injection: breaches/xss_injection.md
    - Web Parameter Tampering: breaches/web_tampering.md
    - Form Tampering: breaches/form_tampering.md
    - Brute Force Credentials: breaches/brute_force.md
    # - File Upload: breaches/file_upload.md
    # - ???: ???
theme:
  name: readthedocs